POST http://localhost:8080/authenticate
content-type: application/json

{
  "username": "tina",
  "password": "password123"
}
> {%
    client.global.set("auth_token", response.headers.valueOf("Authorization"));
    client.log("token: " + response.headers.valueOf("Authorization"));
%}

###
GET http://localhost:8080/api/users
Authorization: {{auth_token}}

###
GET http://localhost:8080/api/users/joanra
Authorization: {{auth_token}}

###
GET http://localhost:8080/api/user
Authorization: {{auth_token}}

###
GET http://localhost:8080/api/users/tina
Authorization: {{auth_token}}

### unexisting user
GET http://localhost:8080/api/users/pepe

###
GET http://localhost:8080/api/stations

###
GET http://localhost:8080/api/stations/La Pobla de Segur


### unexisting station
GET http://localhost:8080/api/stations/La Pobla de Segur

###
GET http://localhost:8080/api/users/joanra/favoriteJourneys
Authorization: {{auth_token}}

###
GET http://localhost:8080/api/user/favoriteJourneys
Authorization: {{auth_token}}

###
POST http://localhost:8080/api/users/joanra/favoriteJourney
Content-Type: application/json

{
  "origin": "Lleida-Pirineus",
  "destination": "Alcoletge",
  "dayTimes": [
    {"dayOfWeek" : "Friday",
      "time" : "12:50"},
    {"dayOfWeek" : "Tuesday",
      "time" : "13:50"}
  ]
}

###
POST http://localhost:8080/api/user/favoriteJourney
Content-Type: application/json
Authorization: {{auth_token}}

{
  "origin": "Lleida-Pirineus",
  "destination": "Alcoletge",
  "dayTimes": [
    {"dayOfWeek" : "Friday",
      "time" : "12:50"},
    {"dayOfWeek" : "Tuesday",
      "time" : "13:50"}
  ]
}

### same origin and destination
POST http://localhost:8080/api/users/joanra/favoriteJourney
Content-Type: application/json

{
  "origin": "Alcoletge",
  "destination": "Alcoletge",
  "dayTimes": [
    {"dayOfWeek" : "Monday",
      "time" : "12:50"},
    {"dayOfWeek" : "Tuesday",
      "time" : "13:50"}
  ]
}

### station name too short
POST http://localhost:8080/api/users/joanra/favoriteJourney
Content-Type: application/json

{
  "origin": "Ll",
  "destination": "Al",
  "dayTimes": [
    {"dayOfWeek" : "onday",
      "time" : "12:0"},
    {"dayOfWeek" : "Tuesday",
      "time" : "a3:50"}
  ]
}

###
GET http://localhost:8080/api/journeys

###
GET http://localhost:8080/api/users/joanra/friends
Authorization: {{auth_token}}

###
GET http://localhost:8080/api/user/friends
Authorization: {{auth_token}}

###
GET http://localhost:8080/api/users/friends

###
POST http://localhost:8080/api/users/friends
Content-Type: application/json

{
  "username": "joanra",
  "friends": [
    "manel",
    "anna",
    "clara"
  ]
}

###
POST http://localhost:8080/api/user/friends
Content-Type: application/json
Authorization: {{auth_token}}

{
  "username": "joanra",
  "friends": [
    "manel",
    "anna",
    "clara"
  ]
}

### incorrect
POST http://localhost:8080/api/users/friends
Content-Type: application/json

{
  "username": "Joanra",
  "friends": []
}

### user does not exist
POST http://localhost:8080/api/users/friends
Content-Type: application/json

{
  "username": "xoanra",
  "friends": ["hola"]
}